---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9071:9071"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9071
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SECURITY_EVENT_LOGGER_EXPORTER_KAFKA_TOPIC_REPLICAS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka_events:
    image: platformatorylabs/trips-kafka-events-producer:1.0.0
    depends_on:
      - kafka
    container_name: kafka_events

  jobmanager:
    image: platformatorylabs/trips-pyflink-feature-processor:1.0.0
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        classloader.check-leaked-classloader: false    

  taskmanager:
    image: platformatorylabs/trips-pyflink-feature-processor:1.0.0
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        classloader.check-leaked-classloader: false
  
  jobrunner:
    image: platformatorylabs/trips-pyflink-feature-processor:1.0.0
    container_name: jobrunner
    depends_on:
      - jobmanager
      - taskmanager
      - kafka_events
    command: /opt/flink/bin/flink run --python /opt/flink/uber/process_trip_data.py --jobmanager jobmanager:8081
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        classloader.check-leaked-classloader: false

  feastserver:
    image: platformatorylabs/trips-feast-server:1.0.0
    container_name: feastserver
    depends_on:
      - postgres
      - redis
      - jobrunner
    ports:
    - "6566:6566"
    command: bash -c "cd feature_repo && feast apply && feast serve -h 0.0.0.0"

  feastingest:
    image: platformatorylabs/trips-feast-server:1.0.0
    container_name: feastingest
    depends_on:
      - feastserver
    command: bash -c "python ingest_stream.py"

  modelapi:
    image: platformatorylabs/trips-ml-server-app:1.0.0
    container_name: modelapi
    ports:
      - "5001:5001"
    depends_on:
      - feastingest

volumes:
  postgres_data:
    driver: local